// Generated by tools/tzgen.py from IANA TZDB. Do not edit by hand.
// Actual transition timestamps 2024-01-01 through 2029-01-01 UTC.
// No Qt, no Intl, no OS zoneinfo at runtime.

function trans(at, offset, abbr) {
    return { at: at, offset: offset, abbr: abbr }
}

function Z(id, cities, abbrs, stdOff, dstOff, stdAbbr, dstAbbr, transitions) {
    return {
        id: id,
        cities: cities,
        abbrs: abbrs,
        stdOffset: stdOff,
        dstOffset: dstOff,
        stdAbbr: stdAbbr,
        dstAbbr: dstAbbr,
        rule: "tzdb",
        transitions: transitions
    }
}

var ZONES = [
    Z("UTC", ["utc", "gmt"], { UTC: 0, GMT: 0 }, 0, 0, "UTC", "UTC", [
            trans(1704067200000, 0, "UTC")
    ]),
    Z("America/New_York", ["new york", "nyc", "boston", "miami", "atlanta", "detroit", "washington"], { EST: -18000, EDT: -14400 }, -18000, -14400, "EST", "EDT", [
            trans(1704067200000, -18000, "EST"),
            trans(1710054000000, -14400, "EDT"),
            trans(1730613600000, -18000, "EST"),
            trans(1741503600000, -14400, "EDT"),
            trans(1762063200000, -18000, "EST"),
            trans(1772953200000, -14400, "EDT"),
            trans(1793512800000, -18000, "EST"),
            trans(1805007600000, -14400, "EDT"),
            trans(1825567200000, -18000, "EST"),
            trans(1836457200000, -14400, "EDT"),
            trans(1857016800000, -18000, "EST")
    ]),
    Z("America/Chicago", ["chicago", "dallas", "houston", "minneapolis"], { CST: -21600, CDT: -18000 }, -21600, -18000, "CST", "CDT", [
            trans(1704067200000, -21600, "CST"),
            trans(1710057600000, -18000, "CDT"),
            trans(1730617200000, -21600, "CST"),
            trans(1741507200000, -18000, "CDT"),
            trans(1762066800000, -21600, "CST"),
            trans(1772956800000, -18000, "CDT"),
            trans(1793516400000, -21600, "CST"),
            trans(1805011200000, -18000, "CDT"),
            trans(1825570800000, -21600, "CST"),
            trans(1836460800000, -18000, "CDT"),
            trans(1857020400000, -21600, "CST")
    ]),
    Z("America/Denver", ["denver", "salt lake city", "salt lake"], { MST: -25200, MDT: -21600 }, -25200, -21600, "MST", "MDT", [
            trans(1704067200000, -25200, "MST"),
            trans(1710061200000, -21600, "MDT"),
            trans(1730620800000, -25200, "MST"),
            trans(1741510800000, -21600, "MDT"),
            trans(1762070400000, -25200, "MST"),
            trans(1772960400000, -21600, "MDT"),
            trans(1793520000000, -25200, "MST"),
            trans(1805014800000, -21600, "MDT"),
            trans(1825574400000, -25200, "MST"),
            trans(1836464400000, -21600, "MDT"),
            trans(1857024000000, -25200, "MST")
    ]),
    Z("America/Los_Angeles", ["los angeles", "la", "seattle", "san francisco", "portland"], { PST: -28800, PDT: -25200 }, -28800, -25200, "PST", "PDT", [
            trans(1704067200000, -28800, "PST"),
            trans(1710064800000, -25200, "PDT"),
            trans(1730624400000, -28800, "PST"),
            trans(1741514400000, -25200, "PDT"),
            trans(1762074000000, -28800, "PST"),
            trans(1772964000000, -25200, "PDT"),
            trans(1793523600000, -28800, "PST"),
            trans(1805018400000, -25200, "PDT"),
            trans(1825578000000, -28800, "PST"),
            trans(1836468000000, -25200, "PDT"),
            trans(1857027600000, -28800, "PST")
    ]),
    Z("America/Phoenix", ["phoenix"], {}, -25200, -25200, "MST", "MST", [
            trans(1704067200000, -25200, "MST")
    ]),
    Z("America/Anchorage", ["anchorage"], { AKST: -32400, AKDT: -28800 }, -32400, -28800, "AKST", "AKDT", [
            trans(1704067200000, -32400, "AKST"),
            trans(1710068400000, -28800, "AKDT"),
            trans(1730628000000, -32400, "AKST"),
            trans(1741518000000, -28800, "AKDT"),
            trans(1762077600000, -32400, "AKST"),
            trans(1772967600000, -28800, "AKDT"),
            trans(1793527200000, -32400, "AKST"),
            trans(1805022000000, -28800, "AKDT"),
            trans(1825581600000, -32400, "AKST"),
            trans(1836471600000, -28800, "AKDT"),
            trans(1857031200000, -32400, "AKST")
    ]),
    Z("Pacific/Honolulu", ["honolulu", "hawaii"], { HST: -36000 }, -36000, -36000, "HST", "HST", [
            trans(1704067200000, -36000, "HST")
    ]),
    Z("America/Toronto", ["toronto"], {}, -18000, -14400, "EST", "EDT", [
            trans(1704067200000, -18000, "EST"),
            trans(1710054000000, -14400, "EDT"),
            trans(1730613600000, -18000, "EST"),
            trans(1741503600000, -14400, "EDT"),
            trans(1762063200000, -18000, "EST"),
            trans(1772953200000, -14400, "EDT"),
            trans(1793512800000, -18000, "EST"),
            trans(1805007600000, -14400, "EDT"),
            trans(1825567200000, -18000, "EST"),
            trans(1836457200000, -14400, "EDT"),
            trans(1857016800000, -18000, "EST")
    ]),
    Z("America/Vancouver", ["vancouver"], {}, -28800, -25200, "PST", "MST", [
            trans(1704067200000, -28800, "PST"),
            trans(1710064800000, -25200, "PDT"),
            trans(1730624400000, -28800, "PST"),
            trans(1741514400000, -25200, "PDT"),
            trans(1762074000000, -28800, "PST"),
            trans(1772964000000, -25200, "PDT"),
            trans(1793523600000, -25200, "MST")
    ]),
    Z("America/Montreal", ["montreal"], {}, -18000, -14400, "EST", "EDT", [
            trans(1704067200000, -18000, "EST"),
            trans(1710054000000, -14400, "EDT"),
            trans(1730613600000, -18000, "EST"),
            trans(1741503600000, -14400, "EDT"),
            trans(1762063200000, -18000, "EST"),
            trans(1772953200000, -14400, "EDT"),
            trans(1793512800000, -18000, "EST"),
            trans(1805007600000, -14400, "EDT"),
            trans(1825567200000, -18000, "EST"),
            trans(1836457200000, -14400, "EDT"),
            trans(1857016800000, -18000, "EST")
    ]),
    Z("America/Mexico_City", ["mexico city"], {}, -21600, -21600, "CST", "CST", [
            trans(1704067200000, -21600, "CST")
    ]),
    Z("America/Sao_Paulo", ["sao paulo", "são paulo"], {}, -10800, -10800, "-03", "-03", [
            trans(1704067200000, -10800, "-03")
    ]),
    Z("America/Buenos_Aires", ["buenos aires"], {}, -10800, -10800, "-03", "-03", [
            trans(1704067200000, -10800, "-03")
    ]),
    Z("Europe/London", ["london"], { BST: 3600 }, 0, 3600, "GMT", "BST", [
            trans(1704067200000, 0, "GMT"),
            trans(1711846800000, 3600, "BST"),
            trans(1729990800000, 0, "GMT"),
            trans(1743296400000, 3600, "BST"),
            trans(1761440400000, 0, "GMT"),
            trans(1774746000000, 3600, "BST"),
            trans(1792890000000, 0, "GMT"),
            trans(1806195600000, 3600, "BST"),
            trans(1824944400000, 0, "GMT"),
            trans(1837645200000, 3600, "BST"),
            trans(1856394000000, 0, "GMT")
    ]),
    Z("Europe/Dublin", ["dublin"], {}, 0, 3600, "GMT", "IST", [
            trans(1704067200000, 0, "GMT"),
            trans(1711846800000, 3600, "IST"),
            trans(1729990800000, 0, "GMT"),
            trans(1743296400000, 3600, "IST"),
            trans(1761440400000, 0, "GMT"),
            trans(1774746000000, 3600, "IST"),
            trans(1792890000000, 0, "GMT"),
            trans(1806195600000, 3600, "IST"),
            trans(1824944400000, 0, "GMT"),
            trans(1837645200000, 3600, "IST"),
            trans(1856394000000, 0, "GMT")
    ]),
    Z("Europe/Paris", ["paris", "brussels", "amsterdam", "madrid", "rome", "berlin", "zurich", "vienna", "prague", "stockholm", "oslo", "copenhagen", "warsaw"], { CET: 3600, CEST: 7200 }, 3600, 7200, "CET", "CEST", [
            trans(1704067200000, 3600, "CET"),
            trans(1711846800000, 7200, "CEST"),
            trans(1729990800000, 3600, "CET"),
            trans(1743296400000, 7200, "CEST"),
            trans(1761440400000, 3600, "CET"),
            trans(1774746000000, 7200, "CEST"),
            trans(1792890000000, 3600, "CET"),
            trans(1806195600000, 7200, "CEST"),
            trans(1824944400000, 3600, "CET"),
            trans(1837645200000, 7200, "CEST"),
            trans(1856394000000, 3600, "CET")
    ]),
    Z("Europe/Lisbon", ["lisbon"], { WET: 0, WEST: 3600 }, 0, 3600, "WET", "WEST", [
            trans(1704067200000, 0, "WET"),
            trans(1711846800000, 3600, "WEST"),
            trans(1729990800000, 0, "WET"),
            trans(1743296400000, 3600, "WEST"),
            trans(1761440400000, 0, "WET"),
            trans(1774746000000, 3600, "WEST"),
            trans(1792890000000, 0, "WET"),
            trans(1806195600000, 3600, "WEST"),
            trans(1824944400000, 0, "WET"),
            trans(1837645200000, 3600, "WEST"),
            trans(1856394000000, 0, "WET")
    ]),
    Z("Europe/Helsinki", ["helsinki", "athens"], { EET: 7200, EEST: 10800 }, 7200, 10800, "EET", "EEST", [
            trans(1704067200000, 7200, "EET"),
            trans(1711846800000, 10800, "EEST"),
            trans(1729990800000, 7200, "EET"),
            trans(1743296400000, 10800, "EEST"),
            trans(1761440400000, 7200, "EET"),
            trans(1774746000000, 10800, "EEST"),
            trans(1792890000000, 7200, "EET"),
            trans(1806195600000, 10800, "EEST"),
            trans(1824944400000, 7200, "EET"),
            trans(1837645200000, 10800, "EEST"),
            trans(1856394000000, 7200, "EET")
    ]),
    Z("Europe/Moscow", ["moscow"], { MSK: 10800 }, 10800, 10800, "MSK", "MSK", [
            trans(1704067200000, 10800, "MSK")
    ]),
    Z("Europe/Istanbul", ["istanbul"], { TRT: 10800 }, 10800, 10800, "+03", "+03", [
            trans(1704067200000, 10800, "+03")
    ]),
    Z("Africa/Cairo", ["cairo"], {}, 7200, 10800, "EET", "EEST", [
            trans(1704067200000, 7200, "EET"),
            trans(1714082400000, 10800, "EEST"),
            trans(1730408400000, 7200, "EET"),
            trans(1745532000000, 10800, "EEST"),
            trans(1761858000000, 7200, "EET"),
            trans(1776981600000, 10800, "EEST"),
            trans(1793307600000, 7200, "EET"),
            trans(1809036000000, 10800, "EEST"),
            trans(1824757200000, 7200, "EET"),
            trans(1840485600000, 10800, "EEST"),
            trans(1856206800000, 7200, "EET")
    ]),
    Z("Africa/Johannesburg", ["johannesburg", "cape town"], { SAST: 7200 }, 7200, 7200, "SAST", "SAST", [
            trans(1704067200000, 7200, "SAST")
    ]),
    Z("Africa/Nairobi", ["nairobi"], { EAT: 10800 }, 10800, 10800, "EAT", "EAT", [
            trans(1704067200000, 10800, "EAT")
    ]),
    Z("Asia/Dubai", ["dubai"], { GST: 14400 }, 14400, 14400, "+04", "+04", [
            trans(1704067200000, 14400, "+04")
    ]),
    Z("Asia/Jerusalem", ["tel aviv", "jerusalem"], {}, 7200, 10800, "IST", "IDT", [
            trans(1704067200000, 7200, "IST"),
            trans(1711670400000, 10800, "IDT"),
            trans(1729983600000, 7200, "IST"),
            trans(1743120000000, 10800, "IDT"),
            trans(1761433200000, 7200, "IST"),
            trans(1774569600000, 10800, "IDT"),
            trans(1792882800000, 7200, "IST"),
            trans(1806019200000, 10800, "IDT"),
            trans(1824937200000, 7200, "IST"),
            trans(1837468800000, 10800, "IDT"),
            trans(1856386800000, 7200, "IST")
    ]),
    Z("Asia/Kolkata", ["mumbai", "delhi", "kolkata", "bangalore", "india"], {}, 19800, 19800, "IST", "IST", [
            trans(1704067200000, 19800, "IST")
    ]),
    Z("Asia/Bangkok", ["bangkok", "jakarta"], { ICT: 25200 }, 25200, 25200, "+07", "+07", [
            trans(1704067200000, 25200, "+07")
    ]),
    Z("Asia/Singapore", ["singapore"], { SGT: 28800 }, 28800, 28800, "+08", "+08", [
            trans(1704067200000, 28800, "+08")
    ]),
    Z("Asia/Hong_Kong", ["hong kong"], { HKT: 28800 }, 28800, 28800, "HKT", "HKT", [
            trans(1704067200000, 28800, "HKT")
    ]),
    Z("Asia/Shanghai", ["shanghai", "beijing", "china"], { CST: 28800 }, 28800, 28800, "CST", "CST", [
            trans(1704067200000, 28800, "CST")
    ]),
    Z("Asia/Taipei", ["taipei"], { CST: 28800 }, 28800, 28800, "CST", "CST", [
            trans(1704067200000, 28800, "CST")
    ]),
    Z("Asia/Manila", ["manila"], { PHT: 28800 }, 28800, 28800, "PST", "PST", [
            trans(1704067200000, 28800, "PST")
    ]),
    Z("Asia/Seoul", ["seoul"], { KST: 32400 }, 32400, 32400, "KST", "KST", [
            trans(1704067200000, 32400, "KST")
    ]),
    Z("Asia/Tokyo", ["tokyo"], { JST: 32400 }, 32400, 32400, "JST", "JST", [
            trans(1704067200000, 32400, "JST")
    ]),
    Z("Australia/Sydney", ["sydney", "melbourne"], { AEST: 36000, AEDT: 39600 }, 36000, 39600, "AEST", "AEDT", [
            trans(1704067200000, 39600, "AEDT"),
            trans(1712419200000, 36000, "AEST"),
            trans(1728144000000, 39600, "AEDT"),
            trans(1743868800000, 36000, "AEST"),
            trans(1759593600000, 39600, "AEDT"),
            trans(1775318400000, 36000, "AEST"),
            trans(1791043200000, 39600, "AEDT"),
            trans(1806768000000, 36000, "AEST"),
            trans(1822492800000, 39600, "AEDT"),
            trans(1838217600000, 36000, "AEST"),
            trans(1853942400000, 39600, "AEDT")
    ]),
    Z("Australia/Perth", ["perth"], { AWST: 28800 }, 28800, 28800, "AWST", "AWST", [
            trans(1704067200000, 28800, "AWST")
    ]),
    Z("Pacific/Auckland", ["auckland"], { NZST: 43200, NZDT: 46800 }, 43200, 46800, "NZST", "NZDT", [
            trans(1704067200000, 46800, "NZDT"),
            trans(1712412000000, 43200, "NZST"),
            trans(1727532000000, 46800, "NZDT"),
            trans(1743861600000, 43200, "NZST"),
            trans(1758981600000, 46800, "NZDT"),
            trans(1775311200000, 43200, "NZST"),
            trans(1790431200000, 46800, "NZDT"),
            trans(1806760800000, 43200, "NZST"),
            trans(1821880800000, 46800, "NZDT"),
            trans(1838210400000, 43200, "NZST"),
            trans(1853330400000, 46800, "NZDT")
    ]),
    Z("America/Bogota", ["bogota"], { COT: -18000 }, -18000, -18000, "-05", "-05", [
            trans(1704067200000, -18000, "-05")
    ]),
    Z("America/Lima", ["lima"], { PET: -18000 }, -18000, -18000, "-05", "-05", [
            trans(1704067200000, -18000, "-05")
    ]),
    Z("America/Santiago", ["santiago"], {}, -14400, -10800, "-04", "-03", [
            trans(1704067200000, -10800, "-03"),
            trans(1712458800000, -14400, "-04"),
            trans(1725768000000, -10800, "-03"),
            trans(1743908400000, -14400, "-04"),
            trans(1757217600000, -10800, "-03"),
            trans(1775358000000, -14400, "-04"),
            trans(1788667200000, -10800, "-03"),
            trans(1806807600000, -14400, "-04"),
            trans(1820116800000, -10800, "-03"),
            trans(1838257200000, -14400, "-04"),
            trans(1851566400000, -10800, "-03")
    ]),
    Z("America/Halifax", ["halifax"], { AST: -14400, ADT: -10800 }, -14400, -10800, "AST", "ADT", [
            trans(1704067200000, -14400, "AST"),
            trans(1710050400000, -10800, "ADT"),
            trans(1730610000000, -14400, "AST"),
            trans(1741500000000, -10800, "ADT"),
            trans(1762059600000, -14400, "AST"),
            trans(1772949600000, -10800, "ADT"),
            trans(1793509200000, -14400, "AST"),
            trans(1805004000000, -10800, "ADT"),
            trans(1825563600000, -14400, "AST"),
            trans(1836453600000, -10800, "ADT"),
            trans(1857013200000, -14400, "AST")
    ]),
    Z("Atlantic/Reykjavik", ["reykjavik", "iceland"], {}, 0, 0, "GMT", "GMT", [
            trans(1704067200000, 0, "GMT")
    ]),
    Z("Africa/Lagos", ["lagos"], { WAT: 3600 }, 3600, 3600, "WAT", "WAT", [
            trans(1704067200000, 3600, "WAT")
    ]),
    Z("Africa/Casablanca", ["casablanca"], {}, 0, 3600, "+00", "+01", [
            trans(1704067200000, 3600, "+01"),
            trans(1710036000000, 0, "+00"),
            trans(1713060000000, 3600, "+01"),
            trans(1740276000000, 0, "+00"),
            trans(1743904800000, 3600, "+01"),
            trans(1771120800000, 0, "+00"),
            trans(1774144800000, 3600, "+01"),
            trans(1789866000000, 0, "+00")
    ]),
    Z("Asia/Riyadh", ["riyadh"], {}, 10800, 10800, "+03", "+03", [
            trans(1704067200000, 10800, "+03")
    ]),
    Z("Asia/Karachi", ["karachi"], { PKT: 18000 }, 18000, 18000, "PKT", "PKT", [
            trans(1704067200000, 18000, "PKT")
    ]),
    Z("Asia/Dhaka", ["dhaka"], {}, 21600, 21600, "+06", "+06", [
            trans(1704067200000, 21600, "+06")
    ]),
    Z("Asia/Yangon", ["yangon", "rangoon"], {}, 23400, 23400, "+0630", "+0630", [
            trans(1704067200000, 23400, "+0630")
    ]),
    Z("Asia/Ho_Chi_Minh", ["ho chi minh", "saigon", "hanoi"], { ICT: 25200 }, 25200, 25200, "+07", "+07", [
            trans(1704067200000, 25200, "+07")
    ]),
    Z("Pacific/Guam", ["guam"], { ChST: 36000 }, 36000, 36000, "ChST", "ChST", [
            trans(1704067200000, 36000, "ChST")
    ]),
    Z("Pacific/Fiji", ["fiji", "suva"], {}, 43200, 43200, "+12", "+12", [
            trans(1704067200000, 43200, "+12")
    ]),
    Z("Pacific/Port_Moresby", ["port moresby"], { PGT: 36000 }, 36000, 36000, "+10", "+10", [
            trans(1704067200000, 36000, "+10")
    ])
]

var CITY_INDEX = null
var ABBR_INDEX = null
var ID_INDEX = null
var CITY_PHRASES = null

function buildIndex() {
    CITY_INDEX = {}
    ABBR_INDEX = {}
    ID_INDEX = {}
    CITY_PHRASES = []
    for (var i = 0; i < ZONES.length; i++) {
        var z = ZONES[i]
        ID_INDEX[z.id.toLowerCase()] = z
        for (var c = 0; c < z.cities.length; c++) {
            var city = z.cities[c].toLowerCase()
            CITY_INDEX[city] = z
            CITY_PHRASES.push(city)
        }
        for (var a in z.abbrs) {
            if (!z.abbrs.hasOwnProperty(a)) continue
            var key = a.toUpperCase()
            if (ABBR_INDEX[key]) {
                ABBR_INDEX[key] = "ambiguous"
            } else {
                ABBR_INDEX[key] = z
            }
        }
    }
    // Ambiguous on purpose: IST (India vs Ireland), CST (US Central vs China).
    ABBR_INDEX.IST = "ambiguous"
    ABBR_INDEX.CST = "ambiguous"
    CITY_PHRASES.sort(function (a, b) { return b.length - a.length })
}

function zoneById(id) {
    if (!ID_INDEX) buildIndex()
    if (!id) return null
    return ID_INDEX[String(id).toLowerCase()] || null
}

function lookupZone(name) {
    if (!CITY_INDEX) buildIndex()
    if (!name) return null
    var raw = String(name).replace(/^\s+|\s+$/g, "")
    var lower = raw.toLowerCase()
    if (ID_INDEX[lower]) return ID_INDEX[lower]
    if (CITY_INDEX[lower]) return CITY_INDEX[lower]
    var up = raw.toUpperCase()
    var abbr = ABBR_INDEX[up]
    if (abbr === "ambiguous") return null
    if (abbr) return abbr
    return null
}

function cityPhrases() {
    if (!CITY_PHRASES) buildIndex()
    return CITY_PHRASES
}

function offsetAt(zone, utcMs) {
    if (!zone) return 0
    if (!zone.transitions || zone.transitions.length === 0) return zone.stdOffset
    var list = zone.transitions
    var off = list[0].offset
    for (var i = 0; i < list.length; i++) {
        if (list[i].at <= utcMs) off = list[i].offset
        else break
    }
    return off
}

function abbrAt(zone, utcMs) {
    if (!zone) return ""
    if (!zone.transitions || zone.transitions.length === 0) return zone.stdAbbr
    var list = zone.transitions
    var abbr = list[0].abbr
    for (var i = 0; i < list.length; i++) {
        if (list[i].at <= utcMs) abbr = list[i].abbr
        else break
    }
    return abbr
}

function localToUtc(y, m, d, hh, mm, zone) {
    var asIfUtc = Date.UTC(y, m - 1, d, hh, mm, 0)
    var guess = asIfUtc - zone.stdOffset * 1000
    var off1 = offsetAt(zone, guess)
    var utc = asIfUtc - off1 * 1000
    var off2 = offsetAt(zone, utc)
    if (off2 !== off1) utc = asIfUtc - off2 * 1000
    return utc
}

function utcToLocal(utcMs, zone) {
    var off = offsetAt(zone, utcMs)
    var local = utcMs + off * 1000
    var dt = new Date(local)
    return {
        y: dt.getUTCFullYear(),
        m: dt.getUTCMonth() + 1,
        d: dt.getUTCDate(),
        hh: dt.getUTCHours(),
        mm: dt.getUTCMinutes(),
        ss: dt.getUTCSeconds(),
        offset: off,
        abbr: abbrAt(zone, utcMs),
        zoneId: zone.id
    }
}

function convertWall(y, m, d, hh, mm, fromZone, toZone) {
    var utc = localToUtc(y, m, d, hh, mm, fromZone)
    return utcToLocal(utc, toZone)
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        ZONES: ZONES,
        zoneById: zoneById,
        lookupZone: lookupZone,
        cityPhrases: cityPhrases,
        offsetAt: offsetAt,
        abbrAt: abbrAt,
        localToUtc: localToUtc,
        utcToLocal: utcToLocal,
        convertWall: convertWall
    }
}
